name: Submit a 3D Print Request
description: Submit a 3D Print Request
title: "[3d-print]: "
labels: ["3d-print"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this print request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Please provide your email below
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: general-comments
    attributes:
      label: About Your Print
      description: Tell us about your print (Dimensions). Also attach your file by dropping it into this text body (STL or 3mf)
      placeholder: Please provide them in mm of length, width, and height
    validations:
      required: true
  - type: dropdown
    id: material
    attributes:
      label: Material
      description: What Material?
      options:
        - PLA
        - PETG
        - I have my own I want to use
        - Don't Know
    validations:
      required: true
